config/routes.rb
Rails.application.routes.draw do
  get 'google_books/new'
  get 'rakutens/rakuten_search'
  # resources :users,only: [:show,:index]
  root to: 'homes#top'
  devise_for :users
  get 'home/about' => 'homes#about'
  resources :books do
    resource :favorites,only:[:create,:destroy]
    resources :post_comments,only:[:create,:destroy]
  end
  resources :users,only: [:show,:index,:edit,:update] do
    resource :relationships, only: [:create, :destroy]
    get "followings" => "relationships#followings",as:"followings"
    get "followers" => "relationships#followers",as:"followers"
  end
  get "search" => "searches#search"
  resources :user_groups do
    get "join" => "user_groups#join"
    get "mail" => "user_groups#mail"
    post "mail_send" => "user_groups#send"
  end

end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  has_many :user_group_members,dependent: :destroy
  has_many :users,through: :user_group_members
  attachment :group_image, destroy: false

  validates :orner_id, uniqueness: true
end

app/controllers/user_groups_controller.rb
class UserGroupsController < ApplicationController
  before_action :ensure_correct_user,{only:[:edit,:update]}
  def ensure_correct_user
    group = UserGroup.find(params[:id])
    unless group.orner_id == current_user.id
      redirect_to user_path(current_user)
    end
  end

  def index
    @groups = UserGroup.all
    @memebers = UserGroupMember.all
    @book = Book.new
  end

  def join
    @group = UserGroup.find(params[:user_group_id])
    @group.users << current_user
    redirect_to user_groups_path
  end

  def new
    @group = UserGroup.new
  end

  def create
    @group = UserGroup.new(group_params)
    # binding.pry
    @group.orner_id = current_user.id
    member = @group.user_group_members.new
    member.user_id = current_user.id
    member.user_group_id = @group.id
    @group.save
    member.save
    redirect_to user_groups_path
  end
  def edit
    @member = UserGroup.find(params[:id])
  end
  def update
    @member = UserGroup.find(params[:id])
    @member.update(group_params)
    redirect_to user_groups_path
  end

  def show
    @book = Book.new
    @group = UserGroup.find(params[:id])
    # @join = UserGroupMember.new
  end

  def destroy
    @group = UserGroup.find(params[:id])
    @group.users.delete(current_user)
    redirect_to user_groups_path
  end

  def mail
    group = UserGroup.find(params[:user_group_id])
    @member = group.users
    @mail = Book.new
    binding.pry
  end

  def mail_send
  end

  private
  def group_params
    params.require(:user_group).permit(:name,:introduction,:group_image)
  end

end

app/helpers/user_groups_helper.rb
module UserGroupsHelper
end

app/views/user_groups/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th></th>
      <th>グループ名</th>
      <th>紹介文</th>
      <th>メンバー数</th>
      <th colspan="2"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
      <tr>
        <td><%= attachment_image_tag(group, :group_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= group.name %></td>
        <td><%= group.introduction %></td>
        <td><%= group.users.count %></td>
        <td>
          <% if group.orner_id == current_user.id %>
              <%= link_to "edit",edit_user_group_path(group),class:"btn btn-info btn-sm" %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_group_path(group) %></td>

      </tr>
    <% end %>
  </tbody>
</table>

app/views/user_groups/_show.html.erb
<table class='table'>
  <tbody>
      <tr>
        <th></th>
        <th>グループ名</th>
        <th>紹介文</th>
        <th>メンバー</th>
        <th></th>
      </tr>
      <tr>
        <td><%= attachment_image_tag(group, :group_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= group.name %></td>
        <td><%= group.introduction %></td>
        <td>
          <% group.users.each do |member| %>
            <%= member.name %></br>
          <% end %>
        </td>
        <td>
          <% if group.orner_id == current_user.id %>
            <%= link_to "edit",edit_user_group_path(group),class:"btn btn-info btn-block", class: "btn btn-sm btn-success" %>
          <% elsif group.users.include?(current_user) %>
            <%= link_to "Leave thos group", user_group_path(group), method: :delete, class: "btn btn-sm btn-danger", data: { disable_with: '退会中...' }  %>
          <% else %>
            <%= link_to "Join this group",user_group_join_path(group), class:"btn btn-sm btn-success", data: { disable_with: '参加中...' } %>
          <% end %>
          <% if group.orner_id == current_user.id %>
            <td>
              <%= link_to
            </td>
          <% end %>

        </td>
      </tr>
  </tbody>
</table>

app/views/user_groups/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@member, local:true do |f| %>
      <%= render 'layouts/errors', obj: @member %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :group_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_groups/index.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>Groups</h2>
            <%= render 'users/info', user: current_user %>
            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Users</h2>
            <%= render 'index',groups: @groups %>
        </div>
    </div>
</div>

app/views/user_groups/mail.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@mail, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_groups/new.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>Create Group</h2>
    <%= form_with model:@group, local:true do |f| %>
      <%= render 'layouts/errors', obj: @group %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :group_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
  </div>
</div>

app/views/user_groups/show.html.erb
<div class="container px-5 px-sm-0">
    <div class="row">
        <div class="col-md-3">
            <h2>Groups</h2>
            <%= render 'users/info', user: current_user %>
            <h2 class="mt-3">New book</h2>
            <%= render 'books/form', book: @book %>
        </div>
        <div class="col-md-8 offset-md-1">
            <h2>Group Details</h2>
            <%= render 'show',group:@group %>
        </div>
    </div>
</div>